name: deployment-pipeline

on:
  push:
    branches:
      - main

  pull_request:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: track short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: install some deps
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: build the app
        run: go build -o our-binary-${{ steps.vars.outputs.sha_short }} .

      - name: run vet and lint
        run: |
          go vet .
          golint .

      - name: run tests
        run: go test -v

      - name: upload binary
        uses: actions/upload-artifact@v3
        with:
          name: our-binary-${{ steps.vars.outputs.sha_short }}
          path: our-binary-${{ steps.vars.outputs.sha_short }}

    build-container:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: track short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: download binary
        uses: actions/download-artifact@v3
        with:
          name: our-binary-${{ steps.vars.outputs.sha_short }}

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: glennadjrussell
          password: dckr_pat_jUyM2RIc9Zvh7LKj3PT36a6l8gk

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: glennadjrussell
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }}
            glennadjrussell/our-binary:latest
            ghcr.io/glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }}
            ghcr.io/glennadjrussell/our-binary:latest
          build-args: |
            SHORT_SHA=${{ steps.vars.outputs.sha_short }}
            #outputs: type=docker,dest=/tmp/image.tar
          outputs: type=docker

      - name: gcloud setup
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0

      - name: gcloud auth
        run: |
          gcloud auth configure-docker

      - name: publish to gcr
        run: |
          docker tag glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }} gcr.io/gh-pipeline/our-binary:${{ steps.vars.outputs.sha_short }}
          docker push gcr.io/gh-pipeline/our-binary:${{ steps.vars.outputs.sha_short }}

      - name: add comment
        runs: echo "Posting a comment about our new container"

